export const EVENT_ADD = 'event_add'
export const EVENT_UPDATE = 'event_update'
export const EVENT_DELETE = 'event_delete'
export const CURRENT_UPDATE = 'current_update'
export const EVENT_LOAD = 'event_load'
export const MESSAGE_SHOW = 'message_show'
export const LOADER_SHOW = 'loader_show'
export const UPDATE_EVENTS = 'update_events'

export const BASE_URL = 'http://localhost:8082'